"undefined"===typeof window.nsp&&(window.nsp={});
(function(d){var e=d.document.getElementById("ns1ps");d.parent!==d&&e&&"script"===e.nodeName.toLowerCase()&&(d=d.parent);var c=d.document;window.P=d.nsp;var a=d.P;a.version||(a.ia=d,a.d=c,a.jobtypes={},a.c={},a.a=0,a.ea="//s.ns1p.net/",a.W="//b.ns1p.net/",a.update="//c.ns1p.net/u.html",a.ha="cs.ns1p.net/u.html",a.version="1536174158",a.ja=function(a,c){c=Number(a.toFixed(c)).toString();return 1>a&&0<a?c.slice(1):c},a.O=function(a){return Math.random().toString(36).slice(2,
a+2)},a.M=function(){return"?t="+a.O(6)},a.f=function(b){var c=a.d.location.protocol;var d=c;void 0!==b&&(c=0==b?"http:":"https:");return"https:"==d&&c!=d?null:c},a.defer=function(a){var b=this;return setTimeout(function(){a.call(b);b=null},10)},a.o=function(a){var b=c.createElement("script"),d=c.getElementsByTagName("script")[0];b.async=!0;b.src=a;d.parentNode.insertBefore(b,d)},a.U=function(){var b=a.xact.j.pop();if(void 0!==b&&void 0!==b.J){var c=a.jobtypes[b.J];void 0!==c&&(b=new c(b),a.a++,b.S(!0))}else 0==
a.a&&(a.fa(),1==a.xact.R&&a.H())},a.g=function(b){null!==b&&a.C.push(b);a.a--;a.U()},a.$=function(a){return a.filter(function(a){return void 0!==a&&void 0!==a.length&&0<a.length}).join()},a.fa=function(){if(a.C.length){var b="";0<a.D.length&&3>a.D.length&&(b="&g="+a.D.join(","));b=a.W+"?v="+a.version+"&a="+a.F+b+"&x="+a.xact.x;void 0!==a.xact.s&&(b+="&s="+a.xact.s);var c=a.$(a.C);""!==c&&(b+="&r="+c);a.o(b)}},a.H=function(){if(void 0!==a.d.body&&a.d.body){var b=a.d.createElement("iframe"),c=a.f();
b.style.display="none";b.src=c+("http:"==c?a.update:a.ha)+"?v="+a.version+"&a="+a.F;a.d.body.appendChild(b)}else setTimeout(a.H,500)},a.r=function(b){a.Y&&0<b.w&&(a.ia.localStorage.t_ns1p=""+((new Date).getTime()+1E3*b.w));a.C=[];a.xact=b;void 0!==b&&void 0!==b.Z?a.B=b.Z.length:a.B=0;a.U()},window.nsp.r=a.r,a.I=function(b,c,d){a.F=b;a.D=c;a.Y=d;a.o(a.d.location.protocol+a.ea+"?v="+a.version+"&a="+b)})})(window);
window.nsp.jobtypes.L=function(d){var e=window.P,c={aborted:!1,a:!0,l:[],da:d.N||10,b:d.N||10,scheme:e.f(d.s),url:e.f(d.s)+"//"+d.h+(d.u||"/a/l.gif"),m:15E3,S:function(a){this.V=!!a;if(void 0===d.i||void 0===d.h||null==c.scheme)e.g(null);else{var b=0===e.B?1:e.B,k=0===this.b?1:this.b;this.ca=setTimeout(c.abort,d.T||this.m*b*k+3E3);void 0!==window.performance&&"function"==typeof window.performance.clearResourceTimings&&window.performance.clearResourceTimings();a&&e.defer(c.K)}},abort:function(a){c.aborted=
!0;clearTimeout(this.ca);c.a&&!a&&c.finish()},K:function(){if(c.aborted||!c.a)return!1;if(c.b)return c.load(c.b--)},X:function(a){return window.performance.getEntriesByType("resource").filter(function(b){return b.name===a&&void 0!==b.requestStart&&0!==b.requestStart&&void 0!==b.responseEnd&&0!==b.responseEnd})[0]},load:function(a){var b=c.url+e.M();return d.x&&void 0!==d.x?c.ba(a,b):c.aa(a,b)},ba:function(a,b){function e(d,e){return function(){c.v(h,a,b,e||f.status||0)}}var f=new XMLHttpRequest,h=
(new Date).getTime();f.open("GET",b);f.responseType="arraybuffer";f.timeout=d.t||c.m;var g=e(!0),l=e(!1,"650");f.addEventListener("error",e(!1));f.addEventListener("load",g);f.addEventListener("timeout",l);f.send();return f},aa:function(a,b){function e(d,e){return function(){g=g.onload=g.onerror=null;clearTimeout(e);c.v(h,a,b,d?200:500)}}var f=0,h=(new Date).getTime(),g=new Image;f=setTimeout(function(){c.v(h,a,b,"650")},d.t||c.m);g.onload=e(!0,f);g.onerror=e(!1,f);g.src=b;return g},v:function(a,
b,d,f){b===c.b+1&&(b=c.X(d),void 0!==b?c.l.push({latency:b.responseEnd-b.requestStart,status:parseInt(f)}):c.l.push({latency:(new Date).getTime()-a,status:parseInt(f)}),3<c.da-c.b&&0===c.l.length&&c.abort(),0===c.b?c.finish():this.V&&e.defer(c.K))},ga:function(a){return d.i+":"+a.map(function(a){return[d.x?"x":"i",a.status?a.status:0,Math.round(a.latency)].join("|")}).join("!")},finish:function(){c.a&&(e.g(this.ga(c.l)),c.a=!1)}};return c};
(function(){function d(d){var c=window.P,a={aborted:!1,a:!0,scheme:c.f(d.s),S:function(){void 0===d.i||null==a.scheme?c.g(null):(window.nsp.c[d.i]=a.G,setTimeout(a.abort,d.T||3E3),c.o(a.scheme+"//"+c.O(10)+"."+(d.h||d.J.toLowerCase()+".ns1p.net")+(d.u||"/a/r.js")+c.M()+"&j="+d.i))},G:function(b){a.a&&(null!=b&&(b=d.i+":"+b),c.g(b),a.a=!1)},abort:function(){a.aborted=!0;a.a&&a.G(null)}};return a}window.nsp.jobtypes.R=d;window.nsp.jobtypes.A=d;window.nsp.jobtypes.E=d})();
(function(d){if("undefined"!=typeof d.__nspid&&1>Math.random()){var e=0,c=1;try{if("localStorage"in d&&null!==d.localStorage){var a=new Date(parseInt(d.localStorage.t_ns1p,10)),b=new Date;e=1;a&&a>b&&(c=0)}}catch(k){}c&&("object"!=typeof d.__nsptags||"undefined"==typeof d.__nsptags.push?d.nsp.I(d.__nspid,[],e):d.nsp.I(d.__nspid,d.__nsptags,e))}}).apply({},[window]);
